# Generated by Django 4.2.3 on 2023-07-19 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uplink',
            fields=[
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('titulo', models.CharField(max_length=40)),
                ('foto', models.ImageField(upload_to='img/')),
                ('links', models.JSONField(default=list)),
                ('links_redes', models.JSONField(default=list)),
            ],
        ),
    ]
