# Generated by Django 4.2.3 on 2023-07-20 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ulplataform', '0002_uplinktheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='uplink',
            name='tema',
            field=models.CharField(default='default-theme', max_length=20),
        ),
    ]
